export const state = () => ({
  works: [
    {
      id: "0",
      name: "Chace People",
      slug: "chace-people",
      type: "Corporate",
      country: "UK, England",
      duration: "2 Months",
      desc: `Chace People is a leading specialist recruitment agency, placing
      senior support staff with high profile clients around the world. They
      connect and they match, creating the three cs of Chace; client,
      consultant and candidate. Chace people works on a project basis
      whereby our teams connect with the best candidates, creating
      opportunities for our clients to work with the most respected talent
      within their specific industries. with the use of technology and our
      in-depth interview and vetting process, we work closely with our
      clients and candidates to ensure that we match the right people with
      the right people.`,
      cover_img: "/images/chace/chace-banner.png",
      heroImg: "/images/chace/chace-fullpage.webp",
      sliderImgs: [],
      website: "https://chacepeople.com/en",
      content: "",
      compareImgs: [
        // { image: "/images/chace/chace-fullpage.webp" },
        // { image: "/images/trowas/trowas-fullpage.webp" },
      ],
      gallery: [
        "/images/chace/chace-banner.png",
        "/images/chace/chace-mockup-2.png",
        "/images/chace/chace-mockup-3.png",
        "/images/chace/chace-mockup-4.png",
        "/images/chace/chace-mockup-5.png",
        "/images/chace/chace-mockup-6.png",
        "/images/chace/chace-mockup-7.png",
      ],
    },
    {
      id: "1",
      name: "Trowas",
      slug: "trowas",
      type: "Corporate",
      country: "Turkey",
      duration: "1 Month",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      cover_img: "/images/trowas/trowas-banner.jpg",
      heroImg: "/images/trowas/trowas-fullpage.webp",
      sliderImgs: [],
      website: "https://trowas.com",
      content: "",
      compareImgs: [],
      gallery: [
        "/images/trowas/trowas-banner.jpg",
        "/images/trowas/trowas-mockup-2.png",
        "/images/trowas/trowas-mockup-3.png",
        "/images/trowas/trowas-mockup-4.png",
        "/images/trowas/trowas-mockup-5.png",
        "/images/trowas/trowas-mockup-6.png",
        "/images/trowas/trowas-mockup-7.png",
      ],
    },
    {
      id: "2",
      name: "Latro",
      slug: "latro",
      type: "Corporate",
      country: "Turkey",
      duration: "3 Months",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      cover_img: "/images/latro/latro-banner.jpg",
      heroImg: "/images/latro/latro-fullpage.webp",
      sliderImgs: [],
      website: "https://latro.com.tr/en",
      content: "",
      compareImgs: [],
      gallery: [
        "/images/latro/latro-banner.jpg",
        "/images/latro/latro-mockup-2.png",
        "/images/latro/latro-mockup-3.png",
        "/images/latro/latro-mockup-4.png",
        "/images/latro/latro-mockup-5.png",
        "/images/latro/latro-mockup-6.png",
        "/images/latro/latro-mockup-7.png",
      ],
    },
    {
      id: "3",
      name: "Dakar Aeroport",
      slug: "dakar-airport",
      type: "Corporate",
      country: "Senegal",
      duration: "3 Months",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      cover_img: "/images/dakar/dakar-banner.jpg",
      heroImg: "/images/dakar/dakar-fullpage.webp",
      sliderImgs: [],
      website: "https://www.dakaraeroport.com/en",
      content: "",
      compareImgs: [],
      gallery: [
        "/images/dakar/dakar-banner.jpg",
        "/images/dakar/dakar-mockup-2.png",
        "/images/dakar/dakar-mockup-3.png",
        "/images/dakar/dakar-mockup-4.png",
        "/images/dakar/dakar-mockup-5.png",
        "/images/dakar/dakar-mockup-6.png",
        "/images/dakar/dakar-mockup-7.png",
      ],
    },
    {
      id: "4",
      name: "Tansu Yacht",
      slug: "tansu-yacht",
      type: "Corporate",
      country: "Turkey",
      duration: "1 Month",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      cover_img: "/images/tansu/tansu-banner.jpg",
      heroImg: "/images/tansu/tansu-fullpage.webp",
      sliderImgs: [],
      website: "#0",
      content: "",
      compareImgs: [],
      gallery: [
        "/images/tansu/tansu-banner.jpg",
        "/images/tansu/tansu-mockup-2.png",
        "/images/tansu/tansu-mockup-3.png",
        "/images/tansu/tansu-mockup-4.png",
        "/images/tansu/tansu-mockup-5.png",
        "/images/tansu/tansu-mockup-6.png",
        "/images/tansu/tansu-mockup-7.png",
      ],
    },
    {
      id: "5",
      name: "Trace Aerospace",
      slug: "trace-aerospace",
      type: "Corporate",
      country: "Turkey",
      duration: "1.5 Months",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      cover_img: "/images/trace/trace-banner.jpg",
      heroImg: "/images/trace/trace-fullpage.webp",
      sliderImgs: [],
      website: "https://tracesaerospace.com/",
      content: "",
      compareImgs: [],
      gallery: ["/images/trace/trace-banner.jpg"],
    },
    {
      id: "6",
      name: "Yaşalar",
      slug: "yasalar",
      type: "Corporate",
      country: "Turkey",
      duration: "2 Months",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      cover_img: "/images/yasalar/yasalar-banner.jpg",
      heroImg: "/images/yasalar/yasalar-fullpage.webp",
      sliderImgs: [],
      website: "https://yasalar.com.tr/en",
      content: "",
      compareImgs: [],
      gallery: [
        "/images/yasalar/yasalar-banner.jpg",
        "/images/yasalar/yasalar-mockup-1.png",
        "/images/yasalar/yasalar-mockup-2.png",
        "/images/yasalar/yasalar-mockup-3.png",
        "/images/yasalar/yasalar-mockup-4.png",
        "/images/yasalar/yasalar-mockup-5.png",
        "/images/yasalar/yasalar-mockup-6.png",
      ],
    },
    {
      id: "7",
      name: "NSK Group",
      slug: "nsk-group",
      type: "Corporate",
      country: "Turkey",
      duration: "3 Months",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      cover_img: "/images/nsk/nsk-banner.jpg",
      heroImg: "/images/nsk/nsk-fullpage.webp",
      sliderImgs: [],
      website: "https://nskgroup.com.tr/en",
      content: "",
      compareImgs: [],
      gallery: [
        "/images/nsk/nsk-banner.jpg",
        "/images/nsk/nsk-mockup-1.png",
        "/images/nsk/nsk-mockup-2.png",
        "/images/nsk/nsk-mockup-3.png",
        "/images/nsk/nsk-mockup-4.png",
        "/images/nsk/nsk-mockup-5.png",
        "/images/nsk/nsk-mockup-6.png",
      ],
    },
    {
      id: "8",
      name: "FCB Interiors",
      slug: "fcb-interiors",
      type: "Corporate",
      country: "Senegal",
      duration: "3 Months",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      cover_img: "/images/fcb/fcb-banner.jpg",
      heroImg: "/images/fcb/fcb-fullpage.webp",
      sliderImgs: [],
      website: "http://www.fcbinteriors.com/tr",
      content: "",
      compareImgs: [],
      gallery: [
        "/images/fcb/fcb-banner.jpg",
        "/images/fcb/fcb-mockup-1.png",
        "/images/fcb/fcb-mockup-2.png",
        "/images/fcb/fcb-mockup-3.png",
        "/images/fcb/fcb-mockup-4.png",
        "/images/fcb/fcb-mockup-5.png",
        "/images/fcb/fcb-mockup-6.png",
      ],
    },
    {
      id: "9",
      name: "Elkon",
      slug: "elkon",
      type: "Corporate",
      country: "Turkey",
      duration: "1 Month",
      cover_img: "/images/elkon/elkon-banner.jpg",
      heroImg: "/images/elkon/elkon-fullpage.webp",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      sliderImgs: [],
      website: "#0",
      content: "",
      compareImgs: [],
      gallery: [
        "/images/elkon/elkon-banner.jpg",
        "/images/elkon/elkon-mockup-1.png",
        "/images/elkon/elkon-mockup-2.png",
        "/images/elkon/elkon-mockup-3.png",
        "/images/elkon/elkon-mockup-4.png",
        "/images/elkon/elkon-mockup-5.png",
        "/images/elkon/elkon-mockup-6.png",
      ],
    },
    {
      id: "10",
      name: "Madamnica",
      slug: "madamnica",
      type: "Corporate",
      country: "Senegal",
      duration: "1.5 Months",
      desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam expedita dolorum cumque, deleniti cum eum.`,
      cover_img: "/images/madamnica/madamnica-banner.jpg",
      heroImg: "/images/madamnica/madamnica-fullpage.webp",
      sliderImgs: [],
      website: "#0",
      content: "",
      compareImgs: [],
      gallery: [
        "/images/madamnica/madamnica-banner.jpg",
        "/images/madamnica/madamnica-mockup-1.png",
        "/images/madamnica/madamnica-mockup-2.png",
        "/images/madamnica/madamnica-mockup-3.png",
        "/images/madamnica/madamnica-mockup-4.png",
        "/images/madamnica/madamnica-mockup-5.png",
        "/images/madamnica/madamnica-mockup-6.png",
      ],
    },
  ],
  awardedWorks: [
    {
      id: 0,
      name: "Latro",
      slug: "latro",
      text: "Kristal Elma Award",
      image: "/images/latro/latro-banner.jpg",
      awardImage: "/images/latro/latro-award-img.png",
      awardImage: "/images/kristal-elma.png",
    },
    {
      id: 1,
      name: "Chace People",
      slug: "chace-people",
      text: "Horizon Gold Award",
      image: "/images/chace/chace-banner.png",
      awardImage: "/images/horizon.png",
    },
    {
      id: 2,
      name: "Trowas",
      slug: "trowas",
      text: "Altın Örümcek Finalist",
      image: "/images/trowas/trowas-banner.jpg",
      awardImage: "/images/altin-orumcek.png",
    },
    {
      id: 3,
      name: "Latro",
      slug: "latro",
      text: "Horizon Silver Award",
      image: "/images/latro/latro-banner.jpg",
      awardImage: "/images/horizon.png",
    },
  ],
  socials: [
    {
      icon: "iconLinkedin",
      link: "https://www.linkedin.com/in/bilgehan-y%C4%B1lmaz-a723b0220/",
    },
    {
      icon: "iconGithub",
      link: "https://github.com/eqber0",
    },
    {
      icon: "iconTwitter",
      link: "https://twitter.com/eqbeR_",
    },
    {
      icon: "iconInstagram",
      link: "https://www.instagram.com/eqber_/",
    },
  ],
  skills: [
    { title: "HTML 5", percent: 87 },
    { title: "CSS", percent: 93 },
    { title: "Javascript", percent: 76 },
    { title: "Vue.js", percent: 66 },
    { title: "Nuxt.js", percent: 57 },
  ],
});

export const getters = {
  works: (state) => state.works,
  socials: (state) => state.socials,
  skills: (state) => state.skills,
};

export const mutations = {};

export const actions = {};
